name: build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
    - nscloud-ubuntu-22.04-amd64-2x4-with-cache
    - nscloud-git-mirror-5gb
    steps:
    - name: Checkout
      uses: namespacelabs/nscloud-checkout-action@v2

    - name: Checkout Dependency [bldr]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/bldr
        ref: tags/v0.3.0
        path: bldr

    - name: Checkout Dependency [tools]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/tools
        ref: tags/v1.8.0-alpha.0
        path: tools

    - name: Checkout Dependency [pkgs]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/pkgs
        ref: tags/v1.8.0-alpha.0
        path: pkgs

    - name: Git config
      run: |
        git config --global user.name ci
        git config --global user.email ci@dorn.haus

    - name: Build [bldr]
      id: bldr
      run: |
        cd "${GITHUB_WORKSPACE}/bldr"
        patch -p1 < "${GITHUB_WORKSPACE}/patches/bldr.patch"
        git add .
        git commit -m patch

        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          PLATFORM=linux/amd64 \
          PUSH=true \
          image-bldr

        echo "tag=$(git describe --tag --always --dirty)" >> $GITHUB_OUTPUT

    - name: Build [tools]
      run: |
        cd "${GITHUB_WORKSPACE}/tools"

        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          BLDR_RELEASE="${{ steps.bldr.outputs.tag }}" \
          BLDR_IMAGE="${NSC_CONTAINER_REGISTRY}/siderolabs/bldr:${{ steps.bldr.outputs.tag }}" \
          PLATFORM=linux/amd64 \
          PUSH=true \
          tools

    - name: Build [pkgs]
      run: |
        cd "${GITHUB_WORKSPACE}/pkgs"
        sed --in-place \
          --expression="s|ghcr.io|${NSC_CONTAINER_REGISTRY}|g" \
          --expression="s|bldr:.*|bldr:${{ steps.bldr.outputs.tag }}|g" \
          Pkgfile
        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          BLDR_RELEASE="${{ steps.bldr.outputs.tag }}" \
          BLDR_IMAGE="${NSC_CONTAINER_REGISTRY}/siderolabs/bldr:${{ steps.bldr.outputs.tag }}" \
          PLATFORM=linux/386 \
          grub

    - name: DEBUG
      uses: namespacelabs/breakpoint-action@v0
      if: failure()
      with:
        duration: 4h
        authorized-users: attilaolah
