name: build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
    - nscloud-ubuntu-22.04-amd64-2x4-with-cache
    - nscloud-cache-size-20gb
    - nscloud-git-mirror-5gb
    steps:
    - name: Git config
      run: |
        git config --global user.name ci
        git config --global user.email ci@dorn.haus

    # Checkout
    - name: Checkout
      uses: namespacelabs/nscloud-checkout-action@v2

    - name: Checkout [bldr]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/bldr
        ref: tags/v0.3.0
        path: bldr

    - name: Checkout [toolchain]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/toolchain
        ref: tags/v0.11.0
        path: toolchain

    - name: Checkout [tools]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/tools
        ref: tags/v1.8.0-alpha.0
        path: tools

    - name: Checkout [pkgs]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/pkgs
        ref: tags/v1.8.0-alpha.0
        path: pkgs

    # Builder
    - name: Prepare [bldr]
      id: bldr
      run: |
        cd "${GITHUB_WORKSPACE}/bldr"
        patch -p1 < "${GITHUB_WORKSPACE}/patches/bldr.patch"
        git add .
        git commit -m patch
        echo "tag=$(git describe --tag --always --dirty)" >> $GITHUB_OUTPUT

    - name: Build [bldr]
      run: |
        cd "${GITHUB_WORKSPACE}/bldr"
        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          PLATFORM=linux/amd64 \
          PUSH=true \
          image-bldr

    # Toolchain
    - name: Prepare [toolchain]
      id: toolchain
      run: |
        cd "${GITHUB_WORKSPACE}/toolchain"
        sed --in-place \
          --expression="s/disable-multilib/enable-multilib/g" \
          **/pkg.yaml
        sed --in-place \
          --expression="s|ghcr.io|${NSC_CONTAINER_REGISTRY}|g" \
          --expression="s|bldr:.*|bldr:${{ steps.bldr.outputs.tag }}|g" \
          Pkgfile
        git add .
        git commit -m patch
        echo "tag=$(git describe --tag --always --dirty)" >> $GITHUB_OUTPUT

    - name: Build [toolchain]
      run: |
        cd "${GITHUB_WORKSPACE}/toolchain"
        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          BLDR_RELEASE="${{ steps.bldr.outputs.tag }}" \
          BLDR_IMAGE="${NSC_CONTAINER_REGISTRY}/siderolabs/bldr:${{ steps.bldr.outputs.tag }}" \
          PLATFORM=linux/amd64 \
          PUSH=true \
          toolchain

    # Tools
    - name: Prepare [tools]
      id: tools
      run: |
        cd "${GITHUB_WORKSPACE}/tools"
        sed --in-place \
          --expression="s|ghcr.io|${NSC_CONTAINER_REGISTRY}|g" \
          --expression="s|bldr:.*|bldr:${{ steps.bldr.outputs.tag }}|g" \
          --expression="s|toolchain:.*|toolchain:${{ steps.toolchain.outputs.tag }}|g" \
          Pkgfile
        git add .
        git commit -m patch
        echo "tag=$(git describe --tag --always --dirty)" >> $GITHUB_OUTPUT

    - name: Build [tools]
      run: |
        cd "${GITHUB_WORKSPACE}/tools"
        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          BLDR_RELEASE="${{ steps.bldr.outputs.tag }}" \
          BLDR_IMAGE="${NSC_CONTAINER_REGISTRY}/siderolabs/bldr:${{ steps.bldr.outputs.tag }}" \
          PLATFORM=linux/amd64 \
          PUSH=true \
          tools

    # Packages
    - name: Prepare [pkgs]
      run: |
        cd "${GITHUB_WORKSPACE}/pkgs"
        sed --in-place \
          --expression="s|ghcr.io|${NSC_CONTAINER_REGISTRY}|g" \
          --expression="s|bldr:.*|bldr:${{ steps.bldr.outputs.tag }}|g" \
          --expression="s|tools:.*|toolchain:${{ steps.tools.outputs.tag }}|g" \
          Pkgfile
        git add .
        git commit -m patch

    - name: Build [pkgs] # debug: only building openssl for now
      run: |
        cd "${GITHUB_WORKSPACE}/pkgs"
        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          BLDR_RELEASE="${{ steps.bldr.outputs.tag }}" \
          BLDR_IMAGE="${NSC_CONTAINER_REGISTRY}/siderolabs/bldr:${{ steps.bldr.outputs.tag }}" \
          PLATFORM=linux/386 \
          openssl

    - name: DEBUG
      uses: namespacelabs/breakpoint-action@v0
      if: failure()
      with:
        duration: 5m
        authorized-users: attilaolah
