name: build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
    - nscloud-ubuntu-22.04-amd64-2x4-with-cache
    - nscloud-cache-size-20gb
    - nscloud-git-mirror-5gb
    steps:
    - name: Git config
      run: |
        git config --global user.name ci
        git config --global user.email ci@dorn.haus

    - name: Checkout
      uses: namespacelabs/nscloud-checkout-action@v2

    - name: Checkout [bldr]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/bldr
        ref: tags/v0.3.0
        path: bldr

    - name: Checkout [tools]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/tools
        ref: tags/v1.8.0-alpha.0
        path: tools

    - name: Checkout [pkgs]
      uses: namespacelabs/nscloud-checkout-action@v2
      with:
        repository: siderolabs/pkgs
        ref: tags/v1.8.0-alpha.0
        path: pkgs

    - name: Prepare [bldr]
      id: bldr
      run: |
        cd "${GITHUB_WORKSPACE}/bldr"
        patch -p1 < "${GITHUB_WORKSPACE}/patches/bldr.patch"
        git add .
        git commit -m patch
        echo "tag=$(git describe --tag --always --dirty)" >> $GITHUB_OUTPUT

    - name: Prepare [pkgs]
      id: pkgs
      run: |
        cd "${GITHUB_WORKSPACE}/pkgs"
        sed --in-place \
          --expression="s|ghcr.io|${NSC_CONTAINER_REGISTRY}|g" \
          --expression="s|bldr:.*|bldr:${{ steps.bldr.outputs.tag }}|g" \
          Pkgfile
        grep --extended-regexp '^TARGETS\s[+]?=\s' Makefile \
          | awk '{print $3}' \
          | tr '\n' ' ' \
          | sed 's/^/targets=/g' \
          >> $GITHUB_OUTPUT

    - name: Build [bldr]
      run: |
        cd "${GITHUB_WORKSPACE}/bldr"
        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          PLATFORM=linux/amd64 \
          PUSH=true \
          image-bldr

    - name: Build [tools]
      run: |
        cd "${GITHUB_WORKSPACE}/tools"
        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          BLDR_RELEASE="${{ steps.bldr.outputs.tag }}" \
          BLDR_IMAGE="${NSC_CONTAINER_REGISTRY}/siderolabs/bldr:${{ steps.bldr.outputs.tag }}" \
          PLATFORM=linux/amd64 \
          PUSH=true \
          tools

    - name: Build [pkgs]
      run: |
        cd "${GITHUB_WORKSPACE}/pkgs"
        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          BLDR_RELEASE="${{ steps.bldr.outputs.tag }}" \
          BLDR_IMAGE="${NSC_CONTAINER_REGISTRY}/siderolabs/bldr:${{ steps.bldr.outputs.tag }}" \
          PLATFORM=linux/386 \
          ca-certificates \
          musl linux-firmware \
          base \
          util-linux raspberrypi-firmware liblzma libseccomp sd-boot \
          liburcu syslinux eudev libaio grub ipxe runc containerd \
          lvm2 libjson-c libpopt flannel-cni kmod \
          cni fhs dosfstools iptables

    - name: Build [openssl debug]
      run: |
        cd "${GITHUB_WORKSPACE}/pkgs"
        make \
          REGISTRY="${NSC_CONTAINER_REGISTRY}" \
          BLDR_RELEASE="${{ steps.bldr.outputs.tag }}" \
          BLDR_IMAGE="${NSC_CONTAINER_REGISTRY}/siderolabs/bldr:${{ steps.bldr.outputs.tag }}" \
          PLATFORM=linux/386 \
          openssl

    - name: DEBUG
      uses: namespacelabs/breakpoint-action@v0
      if: failure()
      with:
        duration: 5m
        authorized-users: attilaolah
