name: poetry-demo

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  debug:
    runs-on: namespace-profile-poetry-demo-2

    steps:
    - name: Checkout
      uses: namespacelabs/nscloud-checkout-action@v2

    - name: Setup Poetry cache
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        path: | # Poetry cache + install dir
          ~/.cache/pypoetry
          ~/.local

    - name: Check Poetry version
      run: poetry --version

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root
      env:
        SETUPTOOLS_USE_DISTUTILSL: stdlib
        PYTHONDONTWRITEBYTECODE: 1

    # TODO:
    - name: DEBUG
      uses: namespacelabs/breakpoint-action@v0
      if: failure()
      with:
        duration: 5m
        authorized-users: attilaolah
