name: poetry-demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
    - nscloud-ubuntu-22.04-amd64-2x4-with-cache
    - nscloud-cache-size-20gb
    - nscloud-git-mirror-5gb

    steps:
    - name: Install dependencies
      run: |
        poetry install --no-interaction -E research -E catboost
      env:
        SETUPTOOLS_USE_DISTUTILSL: stdlib
        PYTHONDONTWRITEBYTECODE: 1
      working-directory: src

    # TODO:
    - name: DEBUG
      uses: namespacelabs/breakpoint-action@v0
      if: failure()
      with:
        duration: 5m
        authorized-users: attilaolah
