name: poetry-demo

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  debug:
    runs-on:
    - nscloud-ubuntu-22.04-amd64-2x4-with-cache
    - nscloud-cache-size-20gb
    - nscloud-git-mirror-5gb

    steps:
    - name: Checkout
      uses: namespacelabs/nscloud-checkout-action@v2

    - name: Install dependencies
      run: |
        mkdir src
        poetry install --no-interaction -E research -E catboost
      env:
        SETUPTOOLS_USE_DISTUTILSL: stdlib
        PYTHONDONTWRITEBYTECODE: 1

    # TODO:
    - name: DEBUG
      uses: namespacelabs/breakpoint-action@v0
      if: failure()
      with:
        duration: 5m
        authorized-users: attilaolah
