name: poetry-demo

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  debug:
    runs-on:
    - nscloud-ubuntu-22.04-amd64-2x4-with-cache
    - nscloud-cache-tag-poetry  # arbitrary tag
    - nscloud-cache-size-20gb
    - nscloud-git-mirror-5gb

    steps:
    - name: Checkout
      uses: namespacelabs/nscloud-checkout-action@v2

    - name: Setup Poetry cache
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        path: | # Poetry cache + install dir
          ~/.cache/pypoetry
          ~/.local

    - name: Determine Poetry version in the cache
      id: poetry
      run: echo "version=$(cat ~/.local/VERSION || echo 0)" >> "$GITHUB_OUTPUT"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      if: steps.poetry.outputs.version != '1.8.3'
      with:
        installer-parallel: true
        virtualenvs-create: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction
      env:
        SETUPTOOLS_USE_DISTUTILSL: stdlib
        PYTHONDONTWRITEBYTECODE: 1

    # TODO:
    - name: DEBUG
      uses: namespacelabs/breakpoint-action@v0
      if: failure()
      with:
        duration: 5m
        authorized-users: attilaolah
